insert into sido_sgg (sido, sgg, sort_seq, input_dt, modify_dt) values ('서울특별시', '종로구',               1, now(), now());
insert into sido_sgg (sido, sgg, sort_seq, input_dt, modify_dt) values ('서울특별시', '중구',                 2, now(), now());
insert into sido_sgg (sido, sgg, sort_seq, input_dt, modify_dt) values ('서울특별시', '용산구',               3, now(), now());
insert into sido_sgg (sido, sgg, sort_seq, input_dt, modify_dt) values ('서울특별시', '성동구',               4, now(), now());
insert into sido_sgg (sido, sgg, sort_seq, input_dt, modify_dt) values ('서울특별시', '광진구',               5, now(), now());
insert into sido_sgg (sido, sgg, sort_seq, input_dt, modify_dt) values ('서울특별시', '동대문구',             6, now(), now());
insert into sido_sgg (sido, sgg, sort_seq, input_dt, modify_dt) values ('서울특별시', '중랑구',               7, now(), now());
insert into sido_sgg (sido, sgg, sort_seq, input_dt, modify_dt) values ('서울특별시', '성북구',               8, now(), now());
insert into sido_sgg (sido, sgg, sort_seq, input_dt, modify_dt) values ('서울특별시', '강북구',               9, now(), now());
insert into sido_sgg (sido, sgg, sort_seq, input_dt, modify_dt) values ('서울특별시', '도봉구',              10, now(), now());
insert into sido_sgg (sido, sgg, sort_seq, input_dt, modify_dt) values ('서울특별시', '노원구',              11, now(), now());
insert into sido_sgg (sido, sgg, sort_seq, input_dt, modify_dt) values ('서울특별시', '은평구',              12, now(), now());
insert into sido_sgg (sido, sgg, sort_seq, input_dt, modify_dt) values ('서울특별시', '서대문구',            13, now(), now());
insert into sido_sgg (sido, sgg, sort_seq, input_dt, modify_dt) values ('서울특별시', '마포구',              14, now(), now());
insert into sido_sgg (sido, sgg, sort_seq, input_dt, modify_dt) values ('서울특별시', '양천구',              15, now(), now());
insert into sido_sgg (sido, sgg, sort_seq, input_dt, modify_dt) values ('서울특별시', '강서구',              16, now(), now());
insert into sido_sgg (sido, sgg, sort_seq, input_dt, modify_dt) values ('서울특별시', '구로구',              17, now(), now());
insert into sido_sgg (sido, sgg, sort_seq, input_dt, modify_dt) values ('서울특별시', '금천구',              18, now(), now());
insert into sido_sgg (sido, sgg, sort_seq, input_dt, modify_dt) values ('서울특별시', '영등포구',            19, now(), now());
insert into sido_sgg (sido, sgg, sort_seq, input_dt, modify_dt) values ('서울특별시', '동작구',              20, now(), now());
insert into sido_sgg (sido, sgg, sort_seq, input_dt, modify_dt) values ('서울특별시', '관악구',              21, now(), now());
insert into sido_sgg (sido, sgg, sort_seq, input_dt, modify_dt) values ('서울특별시', '서초구',              22, now(), now());
insert into sido_sgg (sido, sgg, sort_seq, input_dt, modify_dt) values ('서울특별시', '강남구',              23, now(), now());
insert into sido_sgg (sido, sgg, sort_seq, input_dt, modify_dt) values ('서울특별시', '송파구',              24, now(), now());
insert into sido_sgg (sido, sgg, sort_seq, input_dt, modify_dt) values ('서울특별시', '강동구',              25, now(), now());
insert into sido_sgg (sido, sgg, sort_seq, input_dt, modify_dt) values ('부산광역시', '중구',                26, now(), now());
insert into sido_sgg (sido, sgg, sort_seq, input_dt, modify_dt) values ('부산광역시', '서구',                27, now(), now());
insert into sido_sgg (sido, sgg, sort_seq, input_dt, modify_dt) values ('부산광역시', '동구',                28, now(), now());
insert into sido_sgg (sido, sgg, sort_seq, input_dt, modify_dt) values ('부산광역시', '영도구',              29, now(), now());
insert into sido_sgg (sido, sgg, sort_seq, input_dt, modify_dt) values ('부산광역시', '부산진구',            30, now(), now());
insert into sido_sgg (sido, sgg, sort_seq, input_dt, modify_dt) values ('부산광역시', '동래구',              31, now(), now());
insert into sido_sgg (sido, sgg, sort_seq, input_dt, modify_dt) values ('부산광역시', '남구',                32, now(), now());
insert into sido_sgg (sido, sgg, sort_seq, input_dt, modify_dt) values ('부산광역시', '북구',                33, now(), now());
insert into sido_sgg (sido, sgg, sort_seq, input_dt, modify_dt) values ('부산광역시', '해운대구',            34, now(), now());
insert into sido_sgg (sido, sgg, sort_seq, input_dt, modify_dt) values ('부산광역시', '사하구',              35, now(), now());
insert into sido_sgg (sido, sgg, sort_seq, input_dt, modify_dt) values ('부산광역시', '금정구',              36, now(), now());
insert into sido_sgg (sido, sgg, sort_seq, input_dt, modify_dt) values ('부산광역시', '강서구',              37, now(), now());
insert into sido_sgg (sido, sgg, sort_seq, input_dt, modify_dt) values ('부산광역시', '연제구',              38, now(), now());
insert into sido_sgg (sido, sgg, sort_seq, input_dt, modify_dt) values ('부산광역시', '수영구',              39, now(), now());
insert into sido_sgg (sido, sgg, sort_seq, input_dt, modify_dt) values ('부산광역시', '사상구',              40, now(), now());
insert into sido_sgg (sido, sgg, sort_seq, input_dt, modify_dt) values ('부산광역시', '기장군',              41, now(), now());
insert into sido_sgg (sido, sgg, sort_seq, input_dt, modify_dt) values ('대구광역시', '중구',                42, now(), now());
insert into sido_sgg (sido, sgg, sort_seq, input_dt, modify_dt) values ('대구광역시', '동구',                43, now(), now());
insert into sido_sgg (sido, sgg, sort_seq, input_dt, modify_dt) values ('대구광역시', '서구',                44, now(), now());
insert into sido_sgg (sido, sgg, sort_seq, input_dt, modify_dt) values ('대구광역시', '남구',                45, now(), now());
insert into sido_sgg (sido, sgg, sort_seq, input_dt, modify_dt) values ('대구광역시', '북구',                46, now(), now());
insert into sido_sgg (sido, sgg, sort_seq, input_dt, modify_dt) values ('대구광역시', '수성구',              47, now(), now());
insert into sido_sgg (sido, sgg, sort_seq, input_dt, modify_dt) values ('대구광역시', '달서구',              48, now(), now());
insert into sido_sgg (sido, sgg, sort_seq, input_dt, modify_dt) values ('대구광역시', '달성군',              49, now(), now());
insert into sido_sgg (sido, sgg, sort_seq, input_dt, modify_dt) values ('인천광역시', '중구',                50, now(), now());
insert into sido_sgg (sido, sgg, sort_seq, input_dt, modify_dt) values ('인천광역시', '동구',                51, now(), now());
insert into sido_sgg (sido, sgg, sort_seq, input_dt, modify_dt) values ('인천광역시', '남구',                52, now(), now());
insert into sido_sgg (sido, sgg, sort_seq, input_dt, modify_dt) values ('인천광역시', '연수구',              53, now(), now());
insert into sido_sgg (sido, sgg, sort_seq, input_dt, modify_dt) values ('인천광역시', '남동구',              54, now(), now());
insert into sido_sgg (sido, sgg, sort_seq, input_dt, modify_dt) values ('인천광역시', '부평구',              55, now(), now());
insert into sido_sgg (sido, sgg, sort_seq, input_dt, modify_dt) values ('인천광역시', '계양구',              56, now(), now());
insert into sido_sgg (sido, sgg, sort_seq, input_dt, modify_dt) values ('인천광역시', '서구',                57, now(), now());
insert into sido_sgg (sido, sgg, sort_seq, input_dt, modify_dt) values ('인천광역시', '강화군',              58, now(), now());
insert into sido_sgg (sido, sgg, sort_seq, input_dt, modify_dt) values ('인천광역시', '옹진군',              59, now(), now());
insert into sido_sgg (sido, sgg, sort_seq, input_dt, modify_dt) values ('광주광역시', '동구',                60, now(), now());
insert into sido_sgg (sido, sgg, sort_seq, input_dt, modify_dt) values ('광주광역시', '서구',                61, now(), now());
insert into sido_sgg (sido, sgg, sort_seq, input_dt, modify_dt) values ('광주광역시', '남구',                62, now(), now());
insert into sido_sgg (sido, sgg, sort_seq, input_dt, modify_dt) values ('광주광역시', '북구',                63, now(), now());
insert into sido_sgg (sido, sgg, sort_seq, input_dt, modify_dt) values ('광주광역시', '광산구',              64, now(), now());
insert into sido_sgg (sido, sgg, sort_seq, input_dt, modify_dt) values ('대전광역시', '동구',                65, now(), now());
insert into sido_sgg (sido, sgg, sort_seq, input_dt, modify_dt) values ('대전광역시', '중구',                66, now(), now());
insert into sido_sgg (sido, sgg, sort_seq, input_dt, modify_dt) values ('대전광역시', '서구',                67, now(), now());
insert into sido_sgg (sido, sgg, sort_seq, input_dt, modify_dt) values ('대전광역시', '유성구',              68, now(), now());
insert into sido_sgg (sido, sgg, sort_seq, input_dt, modify_dt) values ('대전광역시', '대덕구',              69, now(), now());
insert into sido_sgg (sido, sgg, sort_seq, input_dt, modify_dt) values ('울산광역시', '중구',                70, now(), now());
insert into sido_sgg (sido, sgg, sort_seq, input_dt, modify_dt) values ('울산광역시', '남구',                71, now(), now());
insert into sido_sgg (sido, sgg, sort_seq, input_dt, modify_dt) values ('울산광역시', '동구',                72, now(), now());
insert into sido_sgg (sido, sgg, sort_seq, input_dt, modify_dt) values ('울산광역시', '북구',                73, now(), now());
insert into sido_sgg (sido, sgg, sort_seq, input_dt, modify_dt) values ('울산광역시', '울주군',              74, now(), now());
insert into sido_sgg (sido, sgg, sort_seq, input_dt, modify_dt) values ('세종특별자치시', '세종특별자치시',  75, now(), now());
insert into sido_sgg (sido, sgg, sort_seq, input_dt, modify_dt) values ('경기도', '수원시 장안구',           76, now(), now());
insert into sido_sgg (sido, sgg, sort_seq, input_dt, modify_dt) values ('경기도', '수원시 권선구',           77, now(), now());
insert into sido_sgg (sido, sgg, sort_seq, input_dt, modify_dt) values ('경기도', '수원시 팔달구',           78, now(), now());
insert into sido_sgg (sido, sgg, sort_seq, input_dt, modify_dt) values ('경기도', '수원시 영통구',           79, now(), now());
insert into sido_sgg (sido, sgg, sort_seq, input_dt, modify_dt) values ('경기도', '성남시 수정구',           80, now(), now());
insert into sido_sgg (sido, sgg, sort_seq, input_dt, modify_dt) values ('경기도', '성남시 중원구',           81, now(), now());
insert into sido_sgg (sido, sgg, sort_seq, input_dt, modify_dt) values ('경기도', '성남시 분당구',           82, now(), now());
insert into sido_sgg (sido, sgg, sort_seq, input_dt, modify_dt) values ('경기도', '의정부시',                83, now(), now());
insert into sido_sgg (sido, sgg, sort_seq, input_dt, modify_dt) values ('경기도', '안양시 만안구',           84, now(), now());
insert into sido_sgg (sido, sgg, sort_seq, input_dt, modify_dt) values ('경기도', '안양시 동안구',           85, now(), now());
insert into sido_sgg (sido, sgg, sort_seq, input_dt, modify_dt) values ('경기도', '부천시',                  86, now(), now());
insert into sido_sgg (sido, sgg, sort_seq, input_dt, modify_dt) values ('경기도', '광명시',                  87, now(), now());
insert into sido_sgg (sido, sgg, sort_seq, input_dt, modify_dt) values ('경기도', '평택시',                  88, now(), now());
insert into sido_sgg (sido, sgg, sort_seq, input_dt, modify_dt) values ('경기도', '동두천시',                89, now(), now());
insert into sido_sgg (sido, sgg, sort_seq, input_dt, modify_dt) values ('경기도', '안산시 상록구',           90, now(), now());
insert into sido_sgg (sido, sgg, sort_seq, input_dt, modify_dt) values ('경기도', '안산시 단원구',           91, now(), now());
insert into sido_sgg (sido, sgg, sort_seq, input_dt, modify_dt) values ('경기도', '고양시 덕양구',           92, now(), now());
insert into sido_sgg (sido, sgg, sort_seq, input_dt, modify_dt) values ('경기도', '고양시 일산동구',         93, now(), now());
insert into sido_sgg (sido, sgg, sort_seq, input_dt, modify_dt) values ('경기도', '고양시 일산서구',         94, now(), now());
insert into sido_sgg (sido, sgg, sort_seq, input_dt, modify_dt) values ('경기도', '과천시',                  95, now(), now());
insert into sido_sgg (sido, sgg, sort_seq, input_dt, modify_dt) values ('경기도', '구리시',                  96, now(), now());
insert into sido_sgg (sido, sgg, sort_seq, input_dt, modify_dt) values ('경기도', '남양주시',                97, now(), now());
insert into sido_sgg (sido, sgg, sort_seq, input_dt, modify_dt) values ('경기도', '오산시',                  98, now(), now());
insert into sido_sgg (sido, sgg, sort_seq, input_dt, modify_dt) values ('경기도', '시흥시',                  99, now(), now());
insert into sido_sgg (sido, sgg, sort_seq, input_dt, modify_dt) values ('경기도', '군포시',                 100, now(), now());
insert into sido_sgg (sido, sgg, sort_seq, input_dt, modify_dt) values ('경기도', '의왕시',                 101, now(), now());
insert into sido_sgg (sido, sgg, sort_seq, input_dt, modify_dt) values ('경기도', '하남시',                 102, now(), now());
insert into sido_sgg (sido, sgg, sort_seq, input_dt, modify_dt) values ('경기도', '용인시 처인구',          103, now(), now());
insert into sido_sgg (sido, sgg, sort_seq, input_dt, modify_dt) values ('경기도', '용인시 기흥구',          104, now(), now());
insert into sido_sgg (sido, sgg, sort_seq, input_dt, modify_dt) values ('경기도', '용인시 수지구',          105, now(), now());
insert into sido_sgg (sido, sgg, sort_seq, input_dt, modify_dt) values ('경기도', '파주시',                 106, now(), now());
insert into sido_sgg (sido, sgg, sort_seq, input_dt, modify_dt) values ('경기도', '이천시',                 107, now(), now());
insert into sido_sgg (sido, sgg, sort_seq, input_dt, modify_dt) values ('경기도', '안성시',                 108, now(), now());
insert into sido_sgg (sido, sgg, sort_seq, input_dt, modify_dt) values ('경기도', '김포시',                 109, now(), now());
insert into sido_sgg (sido, sgg, sort_seq, input_dt, modify_dt) values ('경기도', '화성시',                 110, now(), now());
insert into sido_sgg (sido, sgg, sort_seq, input_dt, modify_dt) values ('경기도', '광주시',                 111, now(), now());
insert into sido_sgg (sido, sgg, sort_seq, input_dt, modify_dt) values ('경기도', '양주시',                 112, now(), now());
insert into sido_sgg (sido, sgg, sort_seq, input_dt, modify_dt) values ('경기도', '포천시',                 113, now(), now());
insert into sido_sgg (sido, sgg, sort_seq, input_dt, modify_dt) values ('경기도', '여주군',                 114, now(), now());
insert into sido_sgg (sido, sgg, sort_seq, input_dt, modify_dt) values ('경기도', '연천군',                 115, now(), now());
insert into sido_sgg (sido, sgg, sort_seq, input_dt, modify_dt) values ('경기도', '가평군',                 116, now(), now());
insert into sido_sgg (sido, sgg, sort_seq, input_dt, modify_dt) values ('경기도', '양평군',                 117, now(), now());
insert into sido_sgg (sido, sgg, sort_seq, input_dt, modify_dt) values ('강원도', '춘천시',                 118, now(), now());
insert into sido_sgg (sido, sgg, sort_seq, input_dt, modify_dt) values ('강원도', '원주시',                 119, now(), now());
insert into sido_sgg (sido, sgg, sort_seq, input_dt, modify_dt) values ('강원도', '강릉시',                 120, now(), now());
insert into sido_sgg (sido, sgg, sort_seq, input_dt, modify_dt) values ('강원도', '동해시',                 121, now(), now());
insert into sido_sgg (sido, sgg, sort_seq, input_dt, modify_dt) values ('강원도', '태백시',                 122, now(), now());
insert into sido_sgg (sido, sgg, sort_seq, input_dt, modify_dt) values ('강원도', '속초시',                 123, now(), now());
insert into sido_sgg (sido, sgg, sort_seq, input_dt, modify_dt) values ('강원도', '삼척시',                 124, now(), now());
insert into sido_sgg (sido, sgg, sort_seq, input_dt, modify_dt) values ('강원도', '홍천군',                 125, now(), now());
insert into sido_sgg (sido, sgg, sort_seq, input_dt, modify_dt) values ('강원도', '횡성군',                 126, now(), now());
insert into sido_sgg (sido, sgg, sort_seq, input_dt, modify_dt) values ('강원도', '영월군',                 127, now(), now());
insert into sido_sgg (sido, sgg, sort_seq, input_dt, modify_dt) values ('강원도', '평창군',                 128, now(), now());
insert into sido_sgg (sido, sgg, sort_seq, input_dt, modify_dt) values ('강원도', '정선군',                 129, now(), now());
insert into sido_sgg (sido, sgg, sort_seq, input_dt, modify_dt) values ('강원도', '철원군',                 130, now(), now());
insert into sido_sgg (sido, sgg, sort_seq, input_dt, modify_dt) values ('강원도', '화천군',                 131, now(), now());
insert into sido_sgg (sido, sgg, sort_seq, input_dt, modify_dt) values ('강원도', '양구군',                 132, now(), now());
insert into sido_sgg (sido, sgg, sort_seq, input_dt, modify_dt) values ('강원도', '인제군',                 133, now(), now());
insert into sido_sgg (sido, sgg, sort_seq, input_dt, modify_dt) values ('강원도', '고성군',                 134, now(), now());
insert into sido_sgg (sido, sgg, sort_seq, input_dt, modify_dt) values ('강원도', '양양군',                 135, now(), now());
insert into sido_sgg (sido, sgg, sort_seq, input_dt, modify_dt) values ('충청북도', '청주시 상당구',        136, now(), now());
insert into sido_sgg (sido, sgg, sort_seq, input_dt, modify_dt) values ('충청북도', '청주시 흥덕구',        137, now(), now());
insert into sido_sgg (sido, sgg, sort_seq, input_dt, modify_dt) values ('충청북도', '청주시 서원구',        138, now(), now());
insert into sido_sgg (sido, sgg, sort_seq, input_dt, modify_dt) values ('충청북도', '청주시 청원구',        139, now(), now());
insert into sido_sgg (sido, sgg, sort_seq, input_dt, modify_dt) values ('충청북도', '충주시',               140, now(), now());
insert into sido_sgg (sido, sgg, sort_seq, input_dt, modify_dt) values ('충청북도', '제천시',               141, now(), now());
insert into sido_sgg (sido, sgg, sort_seq, input_dt, modify_dt) values ('충청북도', '보은군',               142, now(), now());
insert into sido_sgg (sido, sgg, sort_seq, input_dt, modify_dt) values ('충청북도', '옥천군',               143, now(), now());
insert into sido_sgg (sido, sgg, sort_seq, input_dt, modify_dt) values ('충청북도', '영동군',               144, now(), now());
insert into sido_sgg (sido, sgg, sort_seq, input_dt, modify_dt) values ('충청북도', '증평군',               145, now(), now());
insert into sido_sgg (sido, sgg, sort_seq, input_dt, modify_dt) values ('충청북도', '진천군',               146, now(), now());
insert into sido_sgg (sido, sgg, sort_seq, input_dt, modify_dt) values ('충청북도', '괴산군',               147, now(), now());
insert into sido_sgg (sido, sgg, sort_seq, input_dt, modify_dt) values ('충청북도', '음성군',               148, now(), now());
insert into sido_sgg (sido, sgg, sort_seq, input_dt, modify_dt) values ('충청북도', '단양군',               149, now(), now());
insert into sido_sgg (sido, sgg, sort_seq, input_dt, modify_dt) values ('충청남도', '천안시 동남구',        150, now(), now());
insert into sido_sgg (sido, sgg, sort_seq, input_dt, modify_dt) values ('충청남도', '천안시 서북구',        151, now(), now());
insert into sido_sgg (sido, sgg, sort_seq, input_dt, modify_dt) values ('충청남도', '공주시',               152, now(), now());
insert into sido_sgg (sido, sgg, sort_seq, input_dt, modify_dt) values ('충청남도', '보령시',               153, now(), now());
insert into sido_sgg (sido, sgg, sort_seq, input_dt, modify_dt) values ('충청남도', '아산시',               154, now(), now());
insert into sido_sgg (sido, sgg, sort_seq, input_dt, modify_dt) values ('충청남도', '서산시',               155, now(), now());
insert into sido_sgg (sido, sgg, sort_seq, input_dt, modify_dt) values ('충청남도', '논산시',               156, now(), now());
insert into sido_sgg (sido, sgg, sort_seq, input_dt, modify_dt) values ('충청남도', '계룡시',               157, now(), now());
insert into sido_sgg (sido, sgg, sort_seq, input_dt, modify_dt) values ('충청남도', '금산군',               158, now(), now());
insert into sido_sgg (sido, sgg, sort_seq, input_dt, modify_dt) values ('충청남도', '부여군',               159, now(), now());
insert into sido_sgg (sido, sgg, sort_seq, input_dt, modify_dt) values ('충청남도', '서천군',               160, now(), now());
insert into sido_sgg (sido, sgg, sort_seq, input_dt, modify_dt) values ('충청남도', '청양군',               161, now(), now());
insert into sido_sgg (sido, sgg, sort_seq, input_dt, modify_dt) values ('충청남도', '홍성군',               162, now(), now());
insert into sido_sgg (sido, sgg, sort_seq, input_dt, modify_dt) values ('충청남도', '예산군',               163, now(), now());
insert into sido_sgg (sido, sgg, sort_seq, input_dt, modify_dt) values ('충청남도', '태안군',               164, now(), now());
insert into sido_sgg (sido, sgg, sort_seq, input_dt, modify_dt) values ('충청남도', '당진시',               165, now(), now());
insert into sido_sgg (sido, sgg, sort_seq, input_dt, modify_dt) values ('전라북도', '전주시 완산구',        166, now(), now());
insert into sido_sgg (sido, sgg, sort_seq, input_dt, modify_dt) values ('전라북도', '전주시 덕진구',        167, now(), now());
insert into sido_sgg (sido, sgg, sort_seq, input_dt, modify_dt) values ('전라북도', '군산시',               168, now(), now());
insert into sido_sgg (sido, sgg, sort_seq, input_dt, modify_dt) values ('전라북도', '익산시',               169, now(), now());
insert into sido_sgg (sido, sgg, sort_seq, input_dt, modify_dt) values ('전라북도', '정읍시',               170, now(), now());
insert into sido_sgg (sido, sgg, sort_seq, input_dt, modify_dt) values ('전라북도', '남원시',               171, now(), now());
insert into sido_sgg (sido, sgg, sort_seq, input_dt, modify_dt) values ('전라북도', '김제시',               172, now(), now());
insert into sido_sgg (sido, sgg, sort_seq, input_dt, modify_dt) values ('전라북도', '완주군',               173, now(), now());
insert into sido_sgg (sido, sgg, sort_seq, input_dt, modify_dt) values ('전라북도', '진안군',               174, now(), now());
insert into sido_sgg (sido, sgg, sort_seq, input_dt, modify_dt) values ('전라북도', '무주군',               175, now(), now());
insert into sido_sgg (sido, sgg, sort_seq, input_dt, modify_dt) values ('전라북도', '장수군',               176, now(), now());
insert into sido_sgg (sido, sgg, sort_seq, input_dt, modify_dt) values ('전라북도', '임실군',               177, now(), now());
insert into sido_sgg (sido, sgg, sort_seq, input_dt, modify_dt) values ('전라북도', '순창군',               178, now(), now());
insert into sido_sgg (sido, sgg, sort_seq, input_dt, modify_dt) values ('전라북도', '고창군',               179, now(), now());
insert into sido_sgg (sido, sgg, sort_seq, input_dt, modify_dt) values ('전라북도', '부안군',               180, now(), now());
insert into sido_sgg (sido, sgg, sort_seq, input_dt, modify_dt) values ('전라남도', '목포시',               181, now(), now());
insert into sido_sgg (sido, sgg, sort_seq, input_dt, modify_dt) values ('전라남도', '여수시',               182, now(), now());
insert into sido_sgg (sido, sgg, sort_seq, input_dt, modify_dt) values ('전라남도', '순천시',               183, now(), now());
insert into sido_sgg (sido, sgg, sort_seq, input_dt, modify_dt) values ('전라남도', '나주시',               184, now(), now());
insert into sido_sgg (sido, sgg, sort_seq, input_dt, modify_dt) values ('전라남도', '광양시',               185, now(), now());
insert into sido_sgg (sido, sgg, sort_seq, input_dt, modify_dt) values ('전라남도', '담양군',               186, now(), now());
insert into sido_sgg (sido, sgg, sort_seq, input_dt, modify_dt) values ('전라남도', '곡성군',               187, now(), now());
insert into sido_sgg (sido, sgg, sort_seq, input_dt, modify_dt) values ('전라남도', '구례군',               188, now(), now());
insert into sido_sgg (sido, sgg, sort_seq, input_dt, modify_dt) values ('전라남도', '고흥군',               189, now(), now());
insert into sido_sgg (sido, sgg, sort_seq, input_dt, modify_dt) values ('전라남도', '보성군',               190, now(), now());
insert into sido_sgg (sido, sgg, sort_seq, input_dt, modify_dt) values ('전라남도', '화순군',               191, now(), now());
insert into sido_sgg (sido, sgg, sort_seq, input_dt, modify_dt) values ('전라남도', '장흥군',               192, now(), now());
insert into sido_sgg (sido, sgg, sort_seq, input_dt, modify_dt) values ('전라남도', '강진군',               193, now(), now());
insert into sido_sgg (sido, sgg, sort_seq, input_dt, modify_dt) values ('전라남도', '해남군',               194, now(), now());
insert into sido_sgg (sido, sgg, sort_seq, input_dt, modify_dt) values ('전라남도', '영암군',               195, now(), now());
insert into sido_sgg (sido, sgg, sort_seq, input_dt, modify_dt) values ('전라남도', '무안군',               196, now(), now());
insert into sido_sgg (sido, sgg, sort_seq, input_dt, modify_dt) values ('전라남도', '함평군',               197, now(), now());
insert into sido_sgg (sido, sgg, sort_seq, input_dt, modify_dt) values ('전라남도', '영광군',               198, now(), now());
insert into sido_sgg (sido, sgg, sort_seq, input_dt, modify_dt) values ('전라남도', '장성군',               199, now(), now());
insert into sido_sgg (sido, sgg, sort_seq, input_dt, modify_dt) values ('전라남도', '완도군',               200, now(), now());
insert into sido_sgg (sido, sgg, sort_seq, input_dt, modify_dt) values ('전라남도', '진도군',               201, now(), now());
insert into sido_sgg (sido, sgg, sort_seq, input_dt, modify_dt) values ('전라남도', '신안군',               202, now(), now());
insert into sido_sgg (sido, sgg, sort_seq, input_dt, modify_dt) values ('경상북도', '포항시 남구',          203, now(), now());
insert into sido_sgg (sido, sgg, sort_seq, input_dt, modify_dt) values ('경상북도', '포항시 북구',          204, now(), now());
insert into sido_sgg (sido, sgg, sort_seq, input_dt, modify_dt) values ('경상북도', '경주시',               205, now(), now());
insert into sido_sgg (sido, sgg, sort_seq, input_dt, modify_dt) values ('경상북도', '김천시',               206, now(), now());
insert into sido_sgg (sido, sgg, sort_seq, input_dt, modify_dt) values ('경상북도', '안동시',               207, now(), now());
insert into sido_sgg (sido, sgg, sort_seq, input_dt, modify_dt) values ('경상북도', '구미시',               208, now(), now());
insert into sido_sgg (sido, sgg, sort_seq, input_dt, modify_dt) values ('경상북도', '영주시',               209, now(), now());
insert into sido_sgg (sido, sgg, sort_seq, input_dt, modify_dt) values ('경상북도', '영천시',               210, now(), now());
insert into sido_sgg (sido, sgg, sort_seq, input_dt, modify_dt) values ('경상북도', '상주시',               211, now(), now());
insert into sido_sgg (sido, sgg, sort_seq, input_dt, modify_dt) values ('경상북도', '문경시',               212, now(), now());
insert into sido_sgg (sido, sgg, sort_seq, input_dt, modify_dt) values ('경상북도', '경산시',               213, now(), now());
insert into sido_sgg (sido, sgg, sort_seq, input_dt, modify_dt) values ('경상북도', '군위군',               214, now(), now());
insert into sido_sgg (sido, sgg, sort_seq, input_dt, modify_dt) values ('경상북도', '의성군',               215, now(), now());
insert into sido_sgg (sido, sgg, sort_seq, input_dt, modify_dt) values ('경상북도', '청송군',               216, now(), now());
insert into sido_sgg (sido, sgg, sort_seq, input_dt, modify_dt) values ('경상북도', '영양군',               217, now(), now());
insert into sido_sgg (sido, sgg, sort_seq, input_dt, modify_dt) values ('경상북도', '영덕군',               218, now(), now());
insert into sido_sgg (sido, sgg, sort_seq, input_dt, modify_dt) values ('경상북도', '청도군',               219, now(), now());
insert into sido_sgg (sido, sgg, sort_seq, input_dt, modify_dt) values ('경상북도', '고령군',               220, now(), now());
insert into sido_sgg (sido, sgg, sort_seq, input_dt, modify_dt) values ('경상북도', '성주군',               221, now(), now());
insert into sido_sgg (sido, sgg, sort_seq, input_dt, modify_dt) values ('경상북도', '칠곡군',               222, now(), now());
insert into sido_sgg (sido, sgg, sort_seq, input_dt, modify_dt) values ('경상북도', '예천군',               223, now(), now());
insert into sido_sgg (sido, sgg, sort_seq, input_dt, modify_dt) values ('경상북도', '봉화군',               224, now(), now());
insert into sido_sgg (sido, sgg, sort_seq, input_dt, modify_dt) values ('경상북도', '울진군',               225, now(), now());
insert into sido_sgg (sido, sgg, sort_seq, input_dt, modify_dt) values ('경상북도', '울릉군',               226, now(), now());
insert into sido_sgg (sido, sgg, sort_seq, input_dt, modify_dt) values ('경상남도', '창원시 의창구',        227, now(), now());
insert into sido_sgg (sido, sgg, sort_seq, input_dt, modify_dt) values ('경상남도', '창원시 성산구',        228, now(), now());
insert into sido_sgg (sido, sgg, sort_seq, input_dt, modify_dt) values ('경상남도', '창원시 마산합포구',    229, now(), now());
insert into sido_sgg (sido, sgg, sort_seq, input_dt, modify_dt) values ('경상남도', '창원시 마산회원구',    230, now(), now());
insert into sido_sgg (sido, sgg, sort_seq, input_dt, modify_dt) values ('경상남도', '창원시 진해구',        231, now(), now());
insert into sido_sgg (sido, sgg, sort_seq, input_dt, modify_dt) values ('경상남도', '진주시',               232, now(), now());
insert into sido_sgg (sido, sgg, sort_seq, input_dt, modify_dt) values ('경상남도', '통영시',               233, now(), now());
insert into sido_sgg (sido, sgg, sort_seq, input_dt, modify_dt) values ('경상남도', '사천시',               234, now(), now());
insert into sido_sgg (sido, sgg, sort_seq, input_dt, modify_dt) values ('경상남도', '김해시',               235, now(), now());
insert into sido_sgg (sido, sgg, sort_seq, input_dt, modify_dt) values ('경상남도', '밀양시',               236, now(), now());
insert into sido_sgg (sido, sgg, sort_seq, input_dt, modify_dt) values ('경상남도', '거제시',               237, now(), now());
insert into sido_sgg (sido, sgg, sort_seq, input_dt, modify_dt) values ('경상남도', '양산시',               238, now(), now());
insert into sido_sgg (sido, sgg, sort_seq, input_dt, modify_dt) values ('경상남도', '의령군',               239, now(), now());
insert into sido_sgg (sido, sgg, sort_seq, input_dt, modify_dt) values ('경상남도', '함안군',               240, now(), now());
insert into sido_sgg (sido, sgg, sort_seq, input_dt, modify_dt) values ('경상남도', '창녕군',               241, now(), now());
insert into sido_sgg (sido, sgg, sort_seq, input_dt, modify_dt) values ('경상남도', '고성군',               242, now(), now());
insert into sido_sgg (sido, sgg, sort_seq, input_dt, modify_dt) values ('경상남도', '남해군',               243, now(), now());
insert into sido_sgg (sido, sgg, sort_seq, input_dt, modify_dt) values ('경상남도', '하동군',               244, now(), now());
insert into sido_sgg (sido, sgg, sort_seq, input_dt, modify_dt) values ('경상남도', '산청군',               245, now(), now());
insert into sido_sgg (sido, sgg, sort_seq, input_dt, modify_dt) values ('경상남도', '함양군',               246, now(), now());
insert into sido_sgg (sido, sgg, sort_seq, input_dt, modify_dt) values ('경상남도', '거창군',               247, now(), now());
insert into sido_sgg (sido, sgg, sort_seq, input_dt, modify_dt) values ('경상남도', '합천군',               248, now(), now());
insert into sido_sgg (sido, sgg, sort_seq, input_dt, modify_dt) values ('제주특별자치도', '제주시',         249, now(), now());
insert into sido_sgg (sido, sgg, sort_seq, input_dt, modify_dt) values ('제주특별자치도', '서귀포시',       250, now(), now());